const towns = [
  'Aberaeron',
  'Aberdare',
  'Abergavenny',
  'Abergele',
  'Abertillery',
  'Aberystwyth',
  'Abingdon',
  'Accrington',
  'Acle',
  'Acton',
  'Adlington',
  'Alcester',
  'Aldeburgh',
  'Aldershot',
  'Aldridge',
  'Alford',
  'Alfreton',
  'Alnwick',
  'Alsager',
  'Alston',
  'Alton',
  'Alton',
  'Altrincham',
  'Amble',
  'Ambleside',
  'Amersham',
  'Amesbury',
  'Amlwch',
  'Ammanford',
  'Ampthill',
  'Andover',
  'Anston',
  'Appleby in Westmorland',
  'Appley',
  'Arlesey',
  'Arnold',
  'Arundel',
  'Ascot',
  'Ashbourne',
  'Ashburton',
  'Ashby de la Zouch',
  'Ashby Woulds',
  'Ashford',
  'Ashford',
  'Ashington',
  'Ashton in Makerfield',
  'Ashton under Lyne',
  'Askern',
  'Aspatria',
  'Atherstone',
  'Atherton',
  'Attleborough',
  'Audenshaw',
  'Axbridge',
  'Axminster',
  'Aylesbury',
  'Aylsham',
  'Bacup',
  'Bagallit',
  'Baildon',
  'Bakewell',
  'Bala',
  'Baldock',
  'Bampton',
  'Banbury',
  'Bangor',
  'Barking',
  'Barmouth',
  'Barnard Castle',
  'Barnes',
  'Barnet',
  'Barnoldswick',
  'Barnsley',
  'Barnstaple',
  'Barrow Hill and Whittington',
  'Barrow in Furness',
  'Barry',
  'Barton upon Humber',
  'Basildon',
  'Basingstoke',
  'Bath',
  'Batley',
  'Battle',
  'Bawtry',
  'Beaconsfield',
  'Beaminster',
  'Beaumaris',
  'Beaumaris',
  'Bebington',
  'Beccles',
  'Beckenham',
  'Bedale',
  'Bedford',
  'Bedlington',
  'Bedworth',
  'Beeston',
  'Belper',
  'Beltchingley',
  'Benllech',
  'Bentham',
  'Berkeley',
  'Berkhamsted',
  'Berwick upon Tweed',
  'Betws y Coed',
  'Beverley',
  'Bewdley',
  'Bexhill on Sea',
  'Bexley',
  'Bicester',
  'Biddulph',
  'Bideford',
  'Biggleswade',
  'Billericay',
  'Billingham',
  'Bilston',
  'Bingham',
  'Bingley',
  'Birchwood',
  'Birkenhead',
  'Birmingham',
  'Birtley',
  'Bishop Auckland',
  'Bishop\'s Castle',
  'Bishop\'s Stortford',
  'Bishop\'s Waltham',
  'Blackburn',
  'Blackheath',
  'Blackpool',
  'Blackrod',
  'Blackwater and Hawley',
  'Blaenau Ffestiniog',
  'Blaina',
  'Blandford Forum',
  'Blaydon on tyne',
  'Bletchley',
  'Bloxwich',
  'Blyth',
  'Bodmin',
  'Bognor Regis',
  'Bollington',
  'Bolsover',
  'Bolton',
  'Bootle',
  'Bordon',
  'Borehamwood',
  'Boroughbridge',
  'Boston',
  'Bottesford',
  'Bourne',
  'Bournemouth',
  'Bovey Tracey',
  'Bowness on Windermere',
  'Bracebridge',
  'Brackley',
  'Bracknell',
  'Bradford',
  'Bradford on Avon',
  'Brading',
  'Bradley Stoke',
  'Bradninch',
  'Braintree',
  'Brampton',
  'Brandon',
  'Braunstone Town',
  'Brecon',
  'Brentford',
  'Brentwood',
  'Bridgend',
  'Bridgnorth',
  'Bridgwater',
  'Bridlington',
  'Bridport',
  'Brierfield',
  'Brierley',
  'Brierley Hill',
  'Brigg',
  'Brighouse',
  'Brightlingsea',
  'Brighton',
  'Bristol',
  'Brixham',
  'Broadstairs',
  'Bromborough',
  'Bromley',
  'Bromsgrove',
  'Bromyard',
  'Broseley',
  'Brough',
  'Broughton',
  'Broughton',
  'Broughton in Furness',
  'Brownhills',
  'Broxbourne',
  'Bruton',
  'Brynmawr',
  'Buckfastleigh',
  'Buckhurst Hill',
  'Buckingham',
  'Buckley',
  'Bude',
  'Budleigh Salterton',
  'Builth Wells',
  'Bulwell',
  'Bungay',
  'Buntingford',
  'Burford',
  'Burgess Hill',
  'Burgh le Marsh',
  'Burnham on Crouch',
  'Burnham on Sea',
  'Burnley',
  'Burntwood',
  'Burry Port',
  'Burslem',
  'Burton Latimer',
  'Burton upon Trent',
  'Bury',
  'Bury St Edmunds',
  'Bushey',
  'Buxton',
  'Cadishead',
  'Caernarfon',
  'Caerphilly',
  'Caerwys',
  'Caister on Sea',
  'Caistor',
  'Caldicot',
  'Callington',
  'Calne',
  'Camberley',
  'Camborne',
  'Cambridge',
  'Camelford',
  'Cannock',
  'Canterbury',
  'Canvey Island',
  'Cardiff',
  'Cardigan',
  'Carlisle',
  'Carlton',
  'Carlton Colville',
  'Carmarthen',
  'Carnforth',
  'Carrog',
  'Carterton',
  'Castle Cary',
  'Castleford',
  'Cefnllys',
  'Chadderton',
  'Chafford Hundred',
  'Chagford',
  'Chapel en le Frith',
  'Chard',
  'Charlbury',
  'Charlestown',
  'Chatham',
  'Chatteris',
  'Cheadle',
  'Cheadle',
  'Cheadle Hulme',
  'Chelmsford',
  'Cheltenham',
  'Chepstow',
  'Chertsey',
  'Chesham',
  'Cheshunt',
  'Chester',
  'Chester le Street',
  'Chesterfield',
  'Chichester',
  'Chickerell',
  'Chingford',
  'Chippenham',
  'Chipping Campden',
  'Chipping Norton',
  'Chipping Sodbury',
  'Chirk',
  'Chorley',
  'Chorleywood',
  'Christchurch',
  'Chudleigh',
  'Chulmleigh',
  'Church Stretton',
  'Cinderford',
  'Cirencester',
  'Clackwell',
  'Clacton on Sea',
  'Clare',
  'Clay Cross',
  'Clayton le Moors',
  'Cleator Moor',
  'Cleckheaton',
  'Cleethorpes',
  'Cleobury Mortimer',
  'Clevedon',
  'Cleveleys',
  'Clitheroe',
  'Clun',
  'Coal Pool',
  'Coalville',
  'Cockermouth',
  'Coggeshall',
  'Colburn',
  'Colchester',
  'Coleford',
  'Coleshill',
  'Colne',
  'Colwyn Bay',
  'Colyton',
  'Congleton',
  'Coningsby',
  'Conisbrough',
  'Connah\'s Quay',
  'Consett',
  'Conwy',
  'Conwy',
  'Corbridge',
  'Corby',
  'Corringham',
  'Corsham',
  'Corwen',
  'Coseley',
  'Cotgrave',
  'Coventry',
  'Cowbridge',
  'Cowes',
  'Cradley Heath',
  'Cramlington',
  'Cranbrook',
  'Craven Arms',
  'Crawley',
  'Crayford',
  'Crediton',
  'Crewe',
  'Crewkerne',
  'Criccieth',
  'Crickhowell',
  'Cricklade',
  'Cromer',
  'Crook',
  'Crosby',
  'Crowborough',
  'Crowland',
  'Crowle',
  'Crowthorne',
  'Croydon',
  'Croydon',
  'Cuckfield',
  'Cullercoats',
  'Cullompton',
  'Cwmbran',
  'Dagenham',
  'Dalton in Furness',
  'Darlaston',
  'Darley Dale',
  'Darlington',
  'Darsley Park',
  'Dartford',
  'Dartmouth',
  'Darwen',
  'Daventry',
  'Dawley',
  'Dawlish',
  'Deal',
  'Deganwy',
  'Denbigh',
  'Denholme',
  'Denton',
  'Derby',
  'Dereham',
  'Desborough',
  'Devizes',
  'Dewsbury',
  'Didcot',
  'Dinnington',
  'Diss',
  'Dolgellau',
  'Dommoc',
  'Doncaster',
  'Dorchester',
  'Dorchester',
  'Dorking',
  'Dover',
  'Dovercourt',
  'Downham Market',
  'Driffield',
  'Droitwich Spa',
  'Dronfield',
  'Dronfield Woodhouse',
  'Droylsden',
  'Dudley',
  'Dukinfield',
  'Dulverton',
  'Dunstable',
  'Dunston',
  'Dunwich',
  'Durham',
  'Dursley',
  'Eaglescliffe',
  'Ealing',
  'Earl Shilton',
  'Earlestown',
  'Earley',
  'Easingwold',
  'East Cowes',
  'East Grinstead',
  'East Ham',
  'East Retford',
  'Eastbourne',
  'Eastington',
  'Eastleigh',
  'Eastwood',
  'Eastwood',
  'Ebbw Vale',
  'Eccles',
  'Eccleshall',
  'Eckington',
  'Edenbridge',
  'Edgware',
  'Edlington',
  'Edmonton',
  'Egham',
  'Egremont',
  'Elland',
  'Ellesmere',
  'Ellesmere Port',
  'Elstree',
  'Ely',
  'Emsworth',
  'Enfield',
  'Epping',
  'Epsom',
  'Epworth',
  'Erith',
  'Esher',
  'Eston',
  'Eton',
  'Evesham',
  'Ewole',
  'Exeter',
  'Exmouth',
  'Eye',
  'Failsworth',
  'Failsworth',
  'Fairfield',
  'Fairford',
  'Fakenham',
  'Falmouth',
  'Fareham',
  'Faringdon',
  'Farnborough',
  'Farnham',
  'Farnworth',
  'Farsley',
  'Faversham',
  'Fazeley',
  'Featherstone',
  'Felixstowe',
  'Fenny Stratford',
  'Fenton',
  'Ferndown',
  'Ferryhill',
  'Ffestiniog',
  'Filey',
  'Filton',
  'Finchley',
  'Fishguard',
  'Fleet',
  'Fleetwood',
  'Flint',
  'Flitwick',
  'Folkestone',
  'Fordbridge',
  'Fordingbridge',
  'Fordwich',
  'Formby',
  'Fowey',
  'Framlingham',
  'Frinton on Sea',
  'Frodsham',
  'Frome',
  'Fulbourn',
  'Gainsborough',
  'Garforth',
  'Garnant',
  'Garstang',
  'Gateshead',
  'Gellifor',
  'Gillingham',
  'Gillingham',
  'Glanamman',
  'Glastonbury',
  'Glossop',
  'Gloucester',
  'Godalming',
  'Godmanchester',
  'Golbourne',
  'Gomshall',
  'Goodwick',
  'Goole',
  'Gorleston',
  'Gornal',
  'Gorseinon',
  'Gosport',
  'Grange over Sands',
  'Grangetown',
  'Grantham',
  'Grassington',
  'Gratton',
  'Gravesend',
  'Grays',
  'Great Brookham',
  'Great Dunmow',
  'Great Harwood',
  'Great Malvern',
  'Great Torrington',
  'Great Yarmouth',
  'Greater Willington',
  'Greenhill',
  'Grimsby',
  'Guildford',
  'Guisborough',
  'Guiseley',
  'Hadfield',
  'Hadleigh',
  'Hadleigh',
  'Hailsham',
  'Hakin',
  'Halesowen',
  'Halesworth',
  'Halewood',
  'Halifax',
  'Halstead',
  'Haltwhistle',
  'Hanley Grange',
  'Harlech',
  'Harlow',
  'Harpenden',
  'Harrington',
  'Harrogate',
  'Harrow',
  'Hartland',
  'Hartlepool',
  'Harwich',
  'Harworth and Bircotes',
  'Haslemere',
  'Haslingden',
  'Hastings',
  'Hatfield',
  'Hatfield',
  'Hatfield',
  'Hatherleigh',
  'Havant',
  'Haverfordwest',
  'Haverhill',
  'Hawarden',
  'Hawes',
  'Haxby',
  'Hay on Wye',
  'Hayle',
  'Haywards Heath',
  'Heanor',
  'Heathfield',
  'Hebden Bridge',
  'Hebden Royd',
  'Heckmondwike',
  'Hedge End',
  'Hednesford',
  'Hedon',
  'Helmsley',
  'Helston',
  'Hemel Hempstead',
  'Hemsworth',
  'Hendon',
  'Henley in Arden',
  'Henley on Thames',
  'Hereford',
  'Herne Bay',
  'Hertford',
  'Hessle',
  'Heswall',
  'Hetton',
  'Hexham',
  'Heybridge',
  'Heywood',
  'High Wycombe',
  'Higham Ferrers',
  'Highampton',
  'Highbridge',
  'Highcliffe',
  'Highworth',
  'Hinckley',
  'Hindley',
  'Hingham',
  'Hitchin',
  'Hockley',
  'Hoddesdon',
  'Holbeach',
  'Holland on Sea',
  'Holmfirth',
  'Holsworthy',
  'Holt',
  'Holyhead',
  'Holyhead',
  'Holywell',
  'Honiton',
  'Horley',
  'Horncastle',
  'Hornsea',
  'Hornsey',
  'Horsforth',
  'Horsham',
  'Horwich',
  'Houghton le Spring',
  'Houghton Regis',
  'Hove',
  'Howden',
  'Howdon',
  'Hoylake',
  'Hoyland',
  'Hucknall',
  'Huddersfield',
  'Hungerford',
  'Hunstanton',
  'Huntingdon',
  'Huyton',
  'Hyde',
  'Hythe',
  'Hythe',
  'Ilford',
  'Ilfracombe',
  'Ilkeston',
  'Ilkley',
  'Ilminster',
  'Immingham',
  'Ince in Makerfield',
  'Ingatestone',
  'Ingleby Barwick',
  'Ipswich',
  'Irlam',
  'Irthlingborough',
  'Ivybridge',
  'Jarrow',
  'Kearsley',
  'Keighley',
  'Kempston',
  'Kendal',
  'Kenilworth',
  'Kesgrave',
  'Keswick',
  'Kettering',
  'Keynsham',
  'Kidderminster',
  'Kidsgrove',
  'Kidwelly',
  'Killamarsh',
  'Killingworth',
  'Kilton',
  'Kimberley',
  'King\'s Lynn',
  'Kingsbridge',
  'Kingsteignton',
  'Kingston upon Thames',
  'Kingswood',
  'Kington',
  'Kirkby',
  'Kirkby in Ashfield',
  'Kirkby Lonsdale',
  'Kirkby Stephen',
  'Kirkbymoorside',
  'Kirkham',
  'Kirton in Lindsey',
  'Knaresborough',
  'Knighton',
  'Knottingley',
  'Knutsford',
  'Laindon',
  'Lambourn',
  'Lampeter',
  'Lancaster',
  'Langdon Hills',
  'Langley Mill',
  'Langport',
  'Laugharne',
  'Launceston',
  'Leatherhead',
  'Lechlade',
  'Ledbury',
  'Lee on the Solent',
  'Leeds',
  'Leek',
  'Leicester',
  'Leigh',
  'Leigh on Sea',
  'Leighton Buzzard',
  'Leiston',
  'Leominster',
  'Letchworth',
  'Lewes',
  'Leyburn',
  'Leyland',
  'Leyton',
  'Lichfield',
  'Lincoln',
  'Linslade',
  'Liskeard',
  'Little Benton',
  'Little Coates',
  'Littleborough',
  'Littlehampton',
  'Liverpool',
  'Llanberis',
  'Llandeilo',
  'Llandovery',
  'Llandrindod Wells',
  'Llandudno',
  'Llandudno Junction',
  'Llandysul',
  'Llanelli',
  'Llanfachreth',
  'Llanfair Caereinion',
  'Llanfairfechan',
  'Llanfairpwllgwyngyll',
  'Llanfyllin',
  'Llangefni',
  'Llangollen',
  'Llangors',
  'Llanidloes',
  'Llanrwst',
  'Llantrisant',
  'Llantwit Major',
  'Llanwrtyd Wells',
  'Lliw Valey',
  'Loddon',
  'Loftus',
  'London',
  'Long Eaton',
  'Long Sutton',
  'Longbenton',
  'Longridge',
  'Longton',
  'Longtown',
  'Longtown',
  'Looe',
  'Lostwithiel',
  'Loughborough',
  'Loughton',
  'Louth',
  'Low Fell',
  'Lowestoft',
  'Ludgershall',
  'Ludlow',
  'Luton',
  'Lutterworth',
  'Lydd',
  'Lydney',
  'Lye',
  'Lyme Regis',
  'Lymington',
  'Lyndhurst',
  'Lynton',
  'Lytham St Annes',
  'Mablethorpe',
  'Mablethorpe and Sutton',
  'Macclesfield',
  'Machynlleth',
  'Madeley',
  'Maesteg',
  'Maghull',
  'Maidenhead',
  'Maidstone',
  'Maldon',
  'Malmesbury',
  'Malpas',
  'Maltby',
  'Malton',
  'Malvern',
  'Manchester',
  'Manningtree',
  'Mansfield',
  'Marazion',
  'March',
  'Margate',
  'Market Bosworth',
  'Market Deeping',
  'Market Drayton',
  'Market Harborough',
  'Market Rasen',
  'Market Weighton',
  'Marlborough',
  'Marlow',
  'Maryport',
  'Masham',
  'Matlock',
  'Medlar with Wesham',
  'Melbourne',
  'Melksham',
  'Meltham',
  'Melton Mowbray',
  'Menai Bridge',
  'Mere',
  'Merthyr Tydfil',
  'Mexborough',
  'Middle Quinton',
  'Middleham',
  'Middlesbrough',
  'Middleton',
  'Middlewich',
  'Midhurst',
  'Midsomer Norton',
  'Mildenhall',
  'Milford Haven',
  'Millom',
  'Milnrow',
  'Milnthorpe',
  'Milton Keynes',
  'Minchinhampton',
  'Minehead',
  'Minster',
  'Mirfield',
  'Mitcham',
  'Mitcheldean',
  'Modbury',
  'Mold',
  'Monmouth',
  'Montgomery',
  'Morecambe',
  'Moreton in Marsh',
  'Moretonhampstead',
  'Morley',
  'Morpeth',
  'Mossley',
  'Moxley',
  'Much Wenlock',
  'Mytholmroyd',
  'Nailsea',
  'Nailsworth',
  'Nantwich',
  'Narberth',
  'Neath',
  'Needham Market',
  'Nefyn',
  'Neithrop',
  'Nelson',
  'Neston',
  'Netherfield',
  'Netherthorpe',
  'Netherton',
  'New Alresford',
  'New Mills',
  'New Milton',
  'New Quay',
  'New Romney',
  'Newark on Trent',
  'Newbiggin by the Sea',
  'Newbury',
  'Newcastle Emlyn',
  'Newcastle under Lyme',
  'Newcastle upon Tyne',
  'Newent',
  'Newhaven',
  'Newlyn',
  'Newmarket',
  'Newport',
  'Newport Pagnell',
  'Newquay',
  'Newton Abbot',
  'Newton Aycliffe',
  'Newton le Willows',
  'Newtown',
  'Neyland',
  'Normanton',
  'North Camp',
  'North Hykeham',
  'North Petherton',
  'North Shields',
  'North Shoebury',
  'North Tawton',
  'North Walsham',
  'Northallerton',
  'Northam',
  'Northampton',
  'Northfleet',
  'Northleach',
  'Northstowe',
  'Northwich',
  'Norton on Derwent',
  'Norton Radstock',
  'Norwich',
  'Nottingham',
  'Nuneaton',
  'Oadby',
  'Oakengates',
  'Oakham',
  'Okehampton',
  'Old Colwyn',
  'Old Radnor',
  'Oldbury',
  'Oldham',
  'Ollerton',
  'Ollerton and Boughton',
  'Olney',
  'Ongar',
  'Ore Valley',
  'Orford',
  'Orgill',
  'Ormskirk',
  'Orpington',
  'Ossett',
  'Oswaldtwistle',
  'Oswestry',
  'Otley',
  'Otley',
  'Ottery St Mary',
  'Oundle',
  'Over Woodhouse',
  'Overton on Dee',
  'Oxford',
  'Paddock Wood',
  'Padiham',
  'Padstow',
  'Paignton',
  'Painswick',
  'Par',
  'Parkeston',
  'Partington',
  'Patchway',
  'Pateley Bridge',
  'Peacehaven',
  'Pelsall',
  'Pembroke',
  'Pembroke Dock',
  'Penarth',
  'Pendlebury',
  'Penistone',
  'Penkridge',
  'Penmaenmawr',
  'Penrith',
  'Penryn',
  'Penwortham',
  'Penzance',
  'Perry Crofts',
  'Pershore',
  'Peterborough',
  'Peterlee',
  'Petersfield',
  'Petworth',
  'Pickering',
  'Pitsea',
  'Plymouth',
  'Pocklington',
  'Polegate',
  'Pontefract',
  'Ponteland',
  'Pontypridd',
  'Poole',
  'Port Talbot',
  'Portchester',
  'Porth',
  'Porthcawl',
  'Porthleven',
  'Porthmadog',
  'Portishead',
  'Portishead and North Weston',
  'Portland',
  'Portsmouth',
  'Potters Bar',
  'Potton',
  'Poulton le Fylde',
  'Poynton with Worth',
  'Preesall',
  'Prescot',
  'Prestatyn',
  'Presteigne',
  'Preston',
  'Prestwich',
  'Prettlewell',
  'Princes Risborough',
  'Princetown',
  'Prudhoe',
  'Pudsey',
  'Pwllheli',
  'Queenborough',
  'Queensferry',
  'Rackheath',
  'Radcliffe',
  'Radstock',
  'Rainford',
  'Rainham',
  'Rainhill',
  'Ramsbottom',
  'Ramsey',
  'Ramsgate',
  'Raunds',
  'Rawtenstall',
  'Rayleigh',
  'Reading',
  'Redcar',
  'Redditch',
  'Redenhall with Harleston',
  'Redhill',
  'Redruth',
  'Reepham',
  'Reigate',
  'Retford',
  'Rhayader',
  'Rhosllannerchrugog',
  'Rhosnesni',
  'Rhuddlan',
  'Rhyl',
  'Richmond',
  'Richmond',
  'Rickmansworth',
  'Ringwood',
  'Ripley',
  'Ripon',
  'Robin Hood\'s Bay',
  'Rochdale',
  'Rochester',
  'Rochford',
  'Romford',
  'Romsey',
  'Ross on Wye',
  'Rothbury',
  'Rotherham',
  'Rothwell',
  'Rothwell',
  'Rowley Regis',
  'Royal Leamington Spa',
  'Royal Tunbridge Wells',
  'Royal Wootton Bassett',
  'Royston',
  'Royton',
  'Rugby',
  'Rugeley',
  'Runcorn',
  'Ruscote',
  'Rushden',
  'Ruthin',
  'Ryde',
  'Rye',
  'Ryton',
  'Saffron Walden',
  'Salcombe',
  'Sale',
  'Salford',
  'Salisbury',
  'Saltash',
  'Saltburn by the Sea',
  'Saltney',
  'Sandbach',
  'Sandhurst',
  'Sandiacre',
  'Sandown',
  'Sandwich',
  'Sandy',
  'Sawbridgeworth',
  'Saxmundham',
  'Scarborough',
  'Scunthorpe',
  'Seaford',
  'Seaham',
  'Seaton',
  'Sedbergh',
  'Sedgefield',
  'Sedgley',
  'Selby',
  'Selsey',
  'Settle',
  'Sevenoaks',
  'Shaftesbury',
  'Shallcross',
  'Shanklin',
  'Shaw and Crompton',
  'Sheerness',
  'Sheffield',
  'Shefford',
  'Shepshed',
  'Shepton Mallet',
  'Sherborne',
  'Sherburn in Elmet',
  'Sherford',
  'Sheriff Hill',
  'Sheringham',
  'Shifnal',
  'Shildon',
  'Shipley',
  'Shipston on Stour',
  'Shirebrook',
  'Shoeburyness',
  'Shoreham by Sea',
  'Shotton',
  'Shrewsbury',
  'Sidmouth',
  'Silloth',
  'Silsden',
  'Sittingbourne',
  'Skegness',
  'Skelmersdale',
  'Skelton in Cleveland',
  'Skipton',
  'Sleaford',
  'Slough',
  'Smethwick',
  'Snaith',
  'Snodland',
  'Soham',
  'Solihull',
  'Somerton',
  'South Benfleet',
  'South Cave',
  'South Elmsall',
  'South Kirkby and Moorthorpe',
  'South Molton',
  'South Petherton',
  'South Shields',
  'South Woodham Ferrers',
  'Southall',
  'Southam',
  'Southampton',
  'Southborough',
  'Southchurch',
  'Southend on Sea',
  'Southgate',
  'Southminster',
  'Southport',
  'Southsea',
  'Southwark',
  'Southwell',
  'Southwick',
  'Southwick',
  'Southwold',
  'Sowerby Bridge',
  'Spalding',
  'Spennymoor',
  'Spilsby',
  'St Asaph',
  'St Austell',
  'St Blazey',
  'St Clears',
  'St Columb Major',
  'St Davids',
  'St Helens',
  'St Ives',
  'St Ives',
  'St Just',
  'St Mary Cray',
  'St Mawes',
  'St Neots',
  'Stafford',
  'Staines upon Thames',
  'Stainforth',
  'Stalbridge',
  'Stalham',
  'Stalybridge',
  'Stamford',
  'Stanfield le Hope',
  'Stanhope',
  'Stanley',
  'Stapleford',
  'Staveley',
  'Staveley',
  'Stevenage',
  'Steyning',
  'Stockport',
  'Stocksbridge',
  'Stockton on Tees',
  'Stockton on Tees',
  'Stoke on Trent',
  'Stokesley',
  'Stone',
  'Stonehouse',
  'Stony Stratford',
  'Stotfold',
  'Stourbridge',
  'Stourport on Severn',
  'Stow on the Wold',
  'Stowmarket',
  'Stratford upon Avon',
  'Stratton',
  'Street',
  'Stretford',
  'Strood',
  'Stroud',
  'Sturminster Newton',
  'Sudbury',
  'Sunderland',
  'Surbiton',
  'Sutton Coldfield',
  'Sutton in Ashfield',
  'Swadlincote',
  'Swaffham',
  'Swanage',
  'Swanley',
  'Swanscombe and Greenhithe',
  'Swansea',
  'Swindon',
  'Swinton',
  'Swinton',
  'Syston',
  'Tadcaster',
  'Tadley',
  'Tafarnaubach',
  'Talgarth',
  'Tamworth',
  'Taunton',
  'Tavistock',
  'Teignmouth',
  'Telford',
  'Telscombe',
  'Tenbury Wells',
  'Tenby',
  'Tenterden',
  'Tetbury',
  'Tewkesbury',
  'Thame',
  'Thatcham',
  'Thaxted',
  'The Deepings',
  'Thetford',
  'Thirsk',
  'Thornaby on Tees',
  'Thornbury',
  'Thorne',
  'Thornton',
  'Thornton Cleveleys',
  'Thorpe Bay',
  'Thorpe St Andrew',
  'Thrapston',
  'Tickhill',
  'Tidworth',
  'Tilbury',
  'Tipton',
  'Tisbury',
  'Tiverton',
  'Todmorden',
  'Tonbridge',
  'Topsham',
  'Torpoint',
  'Torquay',
  'Totnes',
  'Tottenham',
  'Tottington',
  'Totton',
  'Tow Law',
  'Towcester',
  'Towyn',
  'Tredegar',
  'Tregaron',
  'Tring',
  'Trowbridge',
  'Truro',
  'Tunbridge Wells',
  'Tunstall',
  'Twickenham',
  'Tyldesley',
  'Tynemouth',
  'Tywyn',
  'Uckfield',
  'Ulverston',
  'Uppingham',
  'Upton upon Severn',
  'Usk',
  'Uttoxeter',
  'Uxbridge',
  'Ventnor',
  'Verwood',
  'Wadebridge',
  'Wadhurst',
  'Wainfleet',
  'Wakefield',
  'Walkden',
  'Wallasey',
  'Wallingford',
  'Wallsend',
  'Walsall',
  'Waltham Abbey',
  'Waltham Cross',
  'Walthamstow',
  'Walton on Thames',
  'Walton on the Naze',
  'Wantage',
  'Ware',
  'Wareham',
  'Warminster',
  'Warrington',
  'Warsop',
  'Warwick',
  'Washington',
  'Watchet',
  'Waterlooville',
  'Watford',
  'Wath upon Dearne',
  'Watlington',
  'Watton',
  'Wednesbury',
  'Wednesfield',
  'Wellingborough',
  'Wellington',
  'Wellington',
  'Wells',
  'Wells next the Sea',
  'Welshpool',
  'Welwyn Garden City',
  'Wem',
  'Wembley',
  'Wendover',
  'Wesham',
  'West Bedlington',
  'West Bridgefield',
  'West Bromwich',
  'West Ham',
  'West Malling',
  'West Mersea',
  'West Thurrock',
  'West Tilbury',
  'Westbury',
  'Westcliff on Sea',
  'Westerham',
  'Westgate on Sea',
  'Westhoughton',
  'Weston Otmoor',
  'Weston super Mare',
  'Wetherby',
  'Weybridge',
  'Weymouth',
  'Whaley Bridge',
  'Whiston',
  'Whitby',
  'Whitchurch',
  'Whitchurch',
  'Whitefield',
  'Whitehaven',
  'Whitehill',
  'Whitland',
  'Whitley Bay',
  'Whitnash',
  'Whitstable',
  'Whittlesey',
  'Whitworth',
  'Wickford',
  'Wickham',
  'Wickwar',
  'Widnes',
  'Wigan',
  'Wigston Magna',
  'Wigton',
  'Willenhall',
  'Willesden',
  'Willington',
  'Willington Quay',
  'Wilmslow',
  'Wilton',
  'Wimbledon',
  'Wimborne Minster',
  'Wincanton',
  'Winchcombe',
  'Winchelsea',
  'Winchester',
  'Windermere',
  'Windsor',
  'Windy Nook',
  'Winsford',
  'Winsford',
  'Winslow',
  'Winterton',
  'Wirksworth',
  'Wisbech',
  'Witham',
  'Withernsea',
  'Witney',
  'Wiveliscombe',
  'Wivenhoe',
  'Wixams',
  'Woburn',
  'Woburn Sands',
  'Woking',
  'Wokingham',
  'Wolsingham',
  'Wolverhampton',
  'Wolverton and Greenleys',
  'Wombwell',
  'Wood Green',
  'Woodbridge',
  'Woodley',
  'Woodstock',
  'Wooler',
  'Worcester',
  'Workington',
  'Worksop',
  'Worsley',
  'Worthing',
  'Wotton under Edge',
  'Wragby',
  'Wrexham',
  'Wroxham',
  'Wymondham',
  'Y Felinheli',
  'Yarm',
  'Yarmouth',
  'Yate',
  'Yateley',
  'Yeadon',
  'Yeovil',
  'York'
];
